---
root: true

parser: babel-eslint

env:
  browser: true
  node: false
  mocha: true

globals:
  require: true

rules:
  indent: ["error", 2]
  jsx-quotes: "error"
  new-cap: 0
  semi: ["error", "never"]
